import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Header';
import LatestPosts from '../components/LatestPosts';

import { promises as fs } from 'fs';
import matter from 'gray-matter';


const inter = Inter({ subsets: ['latin'] })

interface Posts {
  slug: string;
  frontmatter: { [key: string]: any }
}

export async function getStaticProps(): Promise<{ props: { posts: Posts[] } }> {
  const files = await fs.readdir('posts')
  const posts = await Promise.all(files.map((fileName: string) => {
      const slug = fileName.replace('.md', '');
      const readMd = fs.readFile(`posts/${fileName}`, 'utf-8');
      const { data: frontmatter } = matter(readMd.toString());

      return { slug, frontmatter };
  }));

  return {props: {posts}}
};


export default function Home({ posts }: { posts: Posts[] }) {
  return (
    <>
      <Head>
        <title>Shumayl.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header/>
        <LatestPosts posts={posts}/>
      </div>      
    </>
  )
}
